Try to set up MySQL for data saving - still not working error on mac "NoSuchMethodError (NoSuchMethodError: The method 'query' was called on null. Receiver: null Tried calling: query("SELECT * FROM practice_app.practice_log"))"